# Generated by Django 4.2.14 on 2024-08-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='desciption',
            new_name='description',
        ),
    ]
