# Generated by Django 4.2.14 on 2024-08-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_desciption_ad_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_star', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('description', models.TextField()),
                ('specification', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('stock', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=100)),
                ('label', models.CharField(choices=[('default', 'default'), ('New', 'New'), ('Hot', 'Hot'), ('Sale', 'Sale')], max_length=100)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
