# Generated by Django 4.2.14 on 2024-09-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('star', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='reviews')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
